### PR TITLE
updates images and go installation

### PR DESCRIPTION
**Pull request by fgeller**
hey @Paxa - just a quick one to update the go installation and referenced images.
let me know if you're interested!

### CODE REVIEW

**Comment by Paxa** [comment]
Thank you 🙏

**Comment by Paxa** [comment]
Pushed new tag `evpavel/kt:13.1.1` to docker (automatic builds doesn't work on free account anymore)

**Comment by fgeller** [comment]
hi @Paxa - thanks for the invite! i accepted it, but would keep the pull request process going so you're aware of the changes. makes sense?

**Comment by Paxa** [comment]
Yes, either is ok for me 👍

**Pull request merged**
